[package]
name = "echotune"
version = "0.1.0-canary-0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
rodio = "0.19.0"
termion = "4.0.2"
termios = "0.3.3"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true

# [profile.profiling]
# inherits = "release"
# debug = true
# strip = false

