[package]
name = "echotune"
version = "0.1.0-canary-1"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
libc = "0.2.159"
parking_lot = "0.12.3"
rodio = "0.19.0"
termios = "0.3.3"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true

# [profile.profiling]
# inherits = "release"
# debug = true
# strip = false

